"""add parser_version to sbc_documents

Revision ID: 89d744f9f2e0
Revises: 509857f7ad7c
Create Date: 2026-09-19 06:55:17.292330+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "89d744f9f2e0"
down_revision: str | Sequence[str] | None = "509857f7ad7c"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("sbc_documents", sa.Column("parser_version", sa.Integer(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("sbc_documents", "parser_version")
    # ### end Alembic commands ###
