"""add profile to users

Revision ID: 446e97d57633
Revises: af1fff6e3932
Create Date: 2026-09-19 02:33:27.736743+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "446e97d57633"
down_revision: str | Sequence[str] | None = "af1fff6e3932"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column("users", sa.Column("zip_code", sa.String(length=5), nullable=True))
    op.add_column("users", sa.Column("date_of_birth", sa.Date(), nullable=True))
    op.add_column("users", sa.Column("county_fips", sa.String(length=5), nullable=True))
    op.add_column(
        "users", sa.Column("county_name", sa.String(length=100), nullable=True)
    )
    op.add_column("users", sa.Column("state", sa.String(length=2), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("users", "state")
    op.drop_column("users", "county_name")
    op.drop_column("users", "county_fips")
    op.drop_column("users", "date_of_birth")
    op.drop_column("users", "zip_code")
    # ### end Alembic commands ###
