"""create zip_counties table

Revision ID: 844542b19a87
Revises: faf714a14048
Create Date: 2026-09-18 22:40:52.791058+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "844542b19a87"
down_revision: str | Sequence[str] | None = "faf714a14048"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "zip_counties",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("zipcode", sa.String(length=5), nullable=False),
        sa.Column("plan_year", sa.Integer(), nullable=False),
        sa.Column("countyfips", sa.String(length=5), nullable=False),
        sa.Column("county_name", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "zipcode",
            "plan_year",
            "countyfips",
            name="uq_zip_counties_zipcode_plan_year_countyfips",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("zip_counties")
    # ### end Alembic commands ###
