"""create message_plans table

Revision ID: af1fff6e3932
Revises: 844542b19a87
Create Date: 2026-09-19 00:14:08.331345+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "af1fff6e3932"
down_revision: str | Sequence[str] | None = "844542b19a87"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "message_plans",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("message_id", sa.UUID(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("hios_plan_id", sa.String(length=32), nullable=False),
        sa.Column("plan_year", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("issuer", sa.String(length=300), nullable=False),
        sa.Column("metal_level", sa.String(length=32), nullable=False),
        sa.Column("plan_type", sa.String(length=32), nullable=False),
        sa.Column("monthly_premium", sa.Numeric(precision=10, scale=2), nullable=True),
        sa.Column("premium_age", sa.Integer(), nullable=True),
        sa.Column(
            "premium_reference", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.Column("deductible", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column("drug_deductible", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.Column(
            "out_of_pocket_max", sa.Numeric(precision=12, scale=2), nullable=True
        ),
        sa.Column("hsa_eligible", sa.Boolean(), nullable=False),
        sa.Column("quality_rating", sa.Integer(), nullable=True),
        sa.Column("county_name", sa.String(length=100), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column("benefits_url", sa.Text(), nullable=True),
        sa.ForeignKeyConstraint(["message_id"], ["messages.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "message_id", "position", name="uq_message_plans_message_id_position"
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("message_plans")
    # ### end Alembic commands ###
