"""create plan catalog tables

Revision ID: faf714a14048
Revises: 22443bd33dee
Create Date: 2026-09-18 19:28:38.267441+00:00

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "faf714a14048"
down_revision: str | Sequence[str] | None = "22443bd33dee"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "issuers",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("hios_issuer_id", sa.String(length=32), nullable=False),
        sa.Column("plan_year", sa.Integer(), nullable=False),
        sa.Column("name", sa.String(length=300), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column("individual_url", sa.Text(), nullable=True),
        sa.Column("toll_free", sa.String(length=64), nullable=True),
        sa.Column("tty", sa.String(length=64), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "hios_issuer_id", "plan_year", name="uq_issuers_hios_issuer_id_plan_year"
        ),
    )
    op.create_table(
        "plans",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("issuer_id", sa.UUID(), nullable=False),
        sa.Column("hios_plan_id", sa.String(length=32), nullable=False),
        sa.Column("plan_year", sa.Integer(), nullable=False),
        sa.Column("marketing_name", sa.String(length=300), nullable=False),
        sa.Column("metal_level", sa.String(length=32), nullable=False),
        sa.Column("plan_type", sa.String(length=32), nullable=False),
        sa.Column("state", sa.String(length=2), nullable=False),
        sa.Column(
            "premium_reference", sa.Numeric(precision=10, scale=2), nullable=True
        ),
        sa.Column("hsa_eligible", sa.Boolean(), nullable=False),
        sa.Column("has_national_network", sa.Boolean(), nullable=False),
        sa.Column("is_standardized_plan", sa.Boolean(), nullable=True),
        sa.Column("quality_rating_global", sa.Integer(), nullable=True),
        sa.Column("quality_rating_clinical", sa.Integer(), nullable=True),
        sa.Column("quality_rating_enrollee", sa.Integer(), nullable=True),
        sa.Column("quality_rating_efficiency", sa.Integer(), nullable=True),
        sa.Column("quality_not_rated_reason", sa.String(length=200), nullable=True),
        sa.Column("benefits_url", sa.Text(), nullable=True),
        sa.Column("brochure_url", sa.Text(), nullable=True),
        sa.Column("formulary_url", sa.Text(), nullable=True),
        sa.Column("network_url", sa.Text(), nullable=True),
        sa.Column(
            "created_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.Column(
            "updated_at",
            sa.DateTime(timezone=True),
            server_default=sa.text("now()"),
            nullable=False,
        ),
        sa.ForeignKeyConstraint(["issuer_id"], ["issuers.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "hios_plan_id", "plan_year", name="uq_plans_hios_plan_id_plan_year"
        ),
    )
    op.create_index("ix_plans_issuer_id", "plans", ["issuer_id"], unique=False)
    op.create_index(
        "ix_plans_plan_year_state_metal_level",
        "plans",
        ["plan_year", "state", "metal_level"],
        unique=False,
    )
    op.create_table(
        "plan_cost_shares",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column("kind", sa.String(length=16), nullable=False),
        sa.Column("cost_share_type", sa.String(length=200), nullable=False),
        sa.Column("csr_variant", sa.String(length=64), nullable=False),
        sa.Column("network_tier", sa.String(length=64), nullable=False),
        sa.Column("family_cost", sa.String(length=32), nullable=False),
        sa.Column("amount", sa.Numeric(precision=12, scale=2), nullable=True),
        sa.CheckConstraint(
            "kind IN ('deductible', 'moop')", name="ck_plan_cost_shares_kind"
        ),
        sa.ForeignKeyConstraint(["plan_id"], ["plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "plan_id",
            "kind",
            "cost_share_type",
            "csr_variant",
            "network_tier",
            "family_cost",
            name="uq_plan_cost_shares_plan_kind_type_csr_tier_family",
        ),
    )
    op.create_table(
        "plan_counties",
        sa.Column("id", sa.UUID(), nullable=False),
        sa.Column("plan_id", sa.UUID(), nullable=False),
        sa.Column("countyfips", sa.String(length=5), nullable=False),
        sa.ForeignKeyConstraint(["plan_id"], ["plans.id"], ondelete="CASCADE"),
        sa.PrimaryKeyConstraint("id"),
        sa.UniqueConstraint(
            "plan_id", "countyfips", name="uq_plan_counties_plan_id_countyfips"
        ),
    )
    op.create_index(
        "ix_plan_counties_countyfips", "plan_counties", ["countyfips"], unique=False
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index("ix_plan_counties_countyfips", table_name="plan_counties")
    op.drop_table("plan_counties")
    op.drop_table("plan_cost_shares")
    op.drop_index("ix_plans_plan_year_state_metal_level", table_name="plans")
    op.drop_index("ix_plans_issuer_id", table_name="plans")
    op.drop_table("plans")
    op.drop_table("issuers")
    # ### end Alembic commands ###
